spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  data:
    mongodb:
      uri: mongodb+srv://amirholya01:amir1365@cluster0.og6zorb.mongodb.net/VideoHub?retryWrites=true&w=majority


videoHub:
  app:
    jwtSecret: Javatar.comSecrectKey================
    jwtExpirationMs: 864000000
  file:
    extension: mp4, mkv, webm, mpg, 3gp, avi, tc
    path: \Users\amirh\OneDrive\Desktop\Final-Bachelor-Project\Final-Bachelor-Project\VideoHub